# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nag < Formula
  desc "A terminal UI for Apple Reminders"
  homepage "https://github.com/oronbz/nag"
  version "0.4.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/oronbz/nag/releases/download/v0.4.0/nag_0.4.0_darwin_all.tar.gz"
  sha256 "489dd703887187c1d07bd0593d04ca32e31f3909bed1de861912ff352cd85906"

  define_method(:install) do
    bin.install "nag"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nag version")
  end
end
